/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/avatar/src/avatar.vue')['default']
    Base: typeof import('./src/components/base/src/base.vue')['default']
    Bifrost: typeof import('./src/components/bifrost/src/bifrost.vue')['default']
    Button: typeof import('./src/components/button/src/button.vue')['default']
    Divider: typeof import('./src/components/divider/src/divider.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    Favicon: typeof import('./src/components/favicon/src/favicon.vue')['default']
    Footer: typeof import('./src/components/footer/src/footer.vue')['default']
    Icon: typeof import('./src/components/icon/src/icon.vue')['default']
    Input: typeof import('./src/components/input/src/input.vue')['default']
    Nav: typeof import('./src/components/nav/src/nav.vue')['default']
    Page: typeof import('./src/components/page/src/page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./src/components/switch/src/switch.vue')['default']
    Text: typeof import('./src/components/text/src/text.vue')['default']
    Transition: typeof import('./src/components/transition/src/transition.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
